const mongoose = require("mongoose");

const signSchema = new mongoose.Schema({
    //define the structure of the data
    //_id is automatically generated by mongodb
    userId:{
        type: mongoose.Schema.Types.ObjectId,
        required: true,
        ref: "User",
    }, 
    name: {
        type: String,
        required: true,
        trim: true,
    }
})

//check if the sign model already exists, if not, create it
module.exports = mongoose.models.Sign || mongoose.model("Sign", signSchema);