const mongoose = require("mongoose");

const mediaAssetSchema = new mongoose.Schema({
    url: {
        type: String,
        required: true,
    },
    publicId: {
        type: String,
        required: true,
    },
    type: {
        type: String,
        enum: ['image', 'video', 'gif'],
        required: true,
    },
    originalName: {
        type: String,
        required: true,
    },
    size: {
        type: Number,
        required: true,
    },
    mimeType: {
        type: String,
        required: true,
    },
    fieldname: {
        type: String,
    },
    width: {
        type: Number,
        default: null,
    },
    height: {
        type: Number,
        default: null,
    },
    duration: {
        type: Number, // For videos - duration in seconds
        default: null,
    },
    transformations: {
        thumbnail: String,
        preview: String,
        fullscreen: String,
        original: String,
    },
    createdAt: {
        type: Date,
        default: Date.now,
    },
    updatedAt: {
        type: Date,
        default: Date.now,
    },
}, { _id: true });

const signSchema = new mongoose.Schema({
    //define the structure of the data
    //_id is automatically generated by mongodb
    userId:{
        type: mongoose.Schema.Types.ObjectId,
        required: true,
        ref: "User",
    }, 
    name: {
        type: String,
        required: true,
        trim: true,
    },
    mediaAsset: {
        type: mediaAssetSchema,
        required: true,
    },
    createdAt: {
        type: Date,
        default: Date.now,
    },
    updatedAt: {
        type: Date,
        default: Date.now,
    },
})

//check if the sign model already exists, if not, create it
module.exports = mongoose.models.Sign || mongoose.model("Sign", signSchema);